### ISSUE TITLE
May there be a new release?

### ISSUE THREAD

**Issue by rugk** [kward/shunit2#100]
The master now contains new contains functions and error checking the return values of the functions etc.

Maybe you can release a new version, so we have a new (signed) release or what is still intended to get into the next release?

**Comment by mika** [comment]
Ping, last release dates back to 2018-01-10, and there were quite some commits since then, maybe we could get a new release? :) Thanks for consideration!

**Comment by oxr463** [comment]
Looks like we can close this one, (See: https://github.com/kward/shunit2/releases/tag/v2.1.8).
