### ISSUE TITLE
Order of arguments in assertContains

### ISSUE THREAD

**Issue by DamianRivas** [kward/shunit2#107]
To follow the convention used by `assertEquals`:

```bash
assertEquals [message] expected actual
```

I propose we switch the order of arguments in `assertContains` to match:

Before:

```
assertContains [message] container content
```

After:

```
assertContains [message] content container
```

This is because `content` is basically assertContains' version of `expected`. We expect `content` to be inside of `container`.

**Comment by rugk** [comment]
You notice this is a real h(e)art _breaking_ change? If people already use this in the tests,  :laughing: 

On the other hand, AFAIK, this `assertContains` is not released yet, so nobody can complain that anyone violated semantic versioning or so here… :wink: 

However, let's talk about the idea itself. IMHO, the current order is okay.
IMHO the comparison does not really work, as "container" is not an "actual" value, but a "value that contains the actual value". So I'd rather compare that whole thing with the usual "hackstack/needle" comparison functions.

But to look at how other testing frameworks are doing it:
* Chai.js [does it as currently done here, i.e. `container/hackstack` `content/needle`](https://www.chaijs.com/api/assert/#notincludehaystack-needle-message)
* [PhpUnit does take the needle first, as you proposed](https://phpunit.de/manual/6.5/en/appendixes.assertions.html#appendixes.assertions.assertContains)
* JUnit [is somewhat special anyway, but takes the needle first, still different syntax afterwards](https://github.com/junit-team/junit4/wiki/Matchers-and-assertthat)
* Ruby [does not really support it, but would take the RegEx/hackstack first](https://stackoverflow.com/questions/16121190/in-ruby-unit-tests-how-to-assert-that-a-string-contains-certain-substring)
* …

Hmm, I need more examples for my standpoint. :wink:

**Comment by kward** [comment]
I agree with rugk that changing this now would be quite bad for anybody using the calls. This is one of those unfortunate situations where this could have been implemented better to start, and we are now stuck with the implementation. Sorry :-/
