### ISSUE TITLE
Does shunit2 can unit test bash script?

### ISSUE THREAD

**Issue by haifenghuang** [kward/shunit2#143]
As the title said, I've some bash scripts, Can I use shunit2 to test my bash script? If it can, then could you give me some hints
on how to do that unit test?

**Comment by williamdes** [comment]
You can check out this repository as an example: https://github.com/williamdes/sql-backup/blob/main/tests.sh

**Comment by haifenghuang** [comment]
Thanks a lot, I'll have a look.
