### ISSUE TITLE
Is alias supported in setUp?

### ISSUE THREAD

**Issue by gqqnbig** [kward/shunit2#151]
```bash
#!/bin/bash

oneTimeSetUp() {
  alias hello='echo hello'
}

testMakeNewSale() {
  hello
}

source shunit2
```

I run it by `./makeNewSaleTest.sh`. The error is

> testMakeNewSale
> ./makeNewSaleTest.sh: line 14: hello: command not found
> shunit2:ERROR testMakeNewSale() returned non-zero return code.
> 
> Ran 1 test.
> 
> FAILED (failures=0)

Is alias supported in setUp/oneTimeSetUp?

shunit2 version is master (47be8b23a46a7897e849f1841f0fb704d34d0f6e).

**Comment by kward** [comment]
`alias` is not supported within shell scripts, only on the command-line.

An alternative solution to what you are trying might be:

```
#!/bin/bash

oneTimeSetUp() {
  hello='echo hello'
}

testMakeNewSale() {
  ${hello}  # hello is a variable, and its value must be retrieved as such.
}

source shunit2
```
