### ISSUE TITLE
shunit2 Debian/Ubuntu packages out of date

### ISSUE THREAD

**Issue by peternewman** [kward/shunit2#155]
Maybe @mrud can fix it for us?

It looks like no-one told the Debian packaging system that it's moved to GitHub, so it's still trying to find releases on Google Code (see the first entry here):
https://tracker.debian.org/pkg/shunit2

**Comment by williamdes** [comment]
Assigned to myself, I will update the packaging

**Comment by williamdes** [comment]
I emailed @mrud about taking over the package maintenance, let's see

**Comment by peternewman** [comment]
I somehow completely missed the fact there's an existing issue in the Debian tracker (well a few):
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=887842

**Comment by peternewman** [comment]
> I emailed @mrud about taking over the package maintenance, let's see

I assume you managed to jump through their spam trap successfully?

**Comment by peternewman** [comment]
> > > I emailed @mrud about taking over the package maintenance, let's see
> > 
> > 
> > I assume you managed to jump through their spam trap successfully?
> 
> Well maybe not

It looks like they just want emailing from their website https://dangel.im/ rather than their GitHub profile.

**Comment by dingobar** [comment]
Any luck with this?

**Comment by williamdes** [comment]
Hi,
I am sorry this got delayed, I still have this todo on my todo list
Any help contacting @mrud to be allowed to change the package is welcome

**Comment by williamdes** [comment]
Sent a mail to https://nm.debian.org/person/osamu/ about taking over the package. As soon as I get access to the repository I will start working on the packaging.

**Comment by osamuaoki** [comment]
Any DD can set you up with write access ... but why me?  Anyway, I invited you.  (FYI: I don't maintain this package.)  I now realize made the last git commit.  (Maybe I didn't upload this due to release freeze etc.)   Anyway, this package needs love.  Please salvage this package ASAP.  The last upload by maintainer was 10 years ago.

**Comment by williamdes** [comment]
> Any DD can set you up with write access ... but why me? Anyway, I invited you. (FYI: I don't maintain this package.) I now realize made the last git commit. (Maybe I didn't upload this due to release freeze etc.) Anyway, this package needs love. Please salvage this package ASAP. The last upload by maintainer was 10 years ago.

Thank you so much !
Can you please grant me DM access on this package too so I can upload new versions ?

**Comment by osamuaoki** [comment]
I don't know if I can do what you asked.

I can sponsor upload .this package once you made lintian clean package if I find time.

Please prompt me with direct mail.

**Comment by osamuaoki** [comment]
You need to fix bug ... log goes ...

#------------------------------------------------------------------------------
# Running the test suite with /bin/bash.
#
shell name: bash
shell version: 5.1.16(1)-release

--- Executing the 'shunit2_misc' test suite. ---
testUnboundVariable
testIssue7
testIssue29
testIssue69
testIssue77
testIssue84
ASSERT:failure message for assertFalse was not generated
shunit2:ERROR testIssue84() returned non-zero return code.
testPrepForSourcing
testEscapeCharInStr
testEscapeCharInStr_specialChars
testExtractTestFunctions
testIssue54
testColors
testColorsWitoutTERM

Ran 13 tests.

FAILED (failures=2)
make[1]: *** [debian/rules:14: override_dh_auto_test] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:5: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2
--------------------------------------------------------------------------------
Build finished at 2022-05-16T12:45:22Z

Finished
--------


+------------------------------------------------------------------------------+
| Cleanup                                                                      |
+------------------------------------------------------------------------------+

Purging /<<BUILDDIR>>
Not cleaning session: cloned chroot in use
E: Build failure (dpkg-buildpackage died)

+------------------------------------------------------------------------------+
| Summary                                                                      |
+------------------------------------------------------------------------------+

Build Architecture: amd64
Build Type: full
Build-Space: 364
Build-Time: 14
Distribution: unstable
Fail-Stage: build
Host Architecture: amd64
Install-Time: 8
Job: /home/osamu/tmp/shunit2/shunit2_2.1.8-1.dsc
Machine Architecture: amd64
Package: shunit2
Package-Time: 31
Source-Version: 2.1.8-1
Space: 364
Status: attempted
Version: 2.1.8-1

**Comment by williamdes** [comment]
Sure, this is https://salsa.debian.org/debian/shunit2/-/jobs/2774041#L1005 for issue #121 you commented on
I pushed a patch to apply https://github.com/cezanne/shunit2/commit/e736e3e789a7f8fc04aa8959aec55356554b9ea8 but this did not work

**Comment by williamdes** [comment]
The test passes !
https://salsa.debian.org/debian/shunit2/-/pipelines/410390

I made lintian happy as much as possible
@osamuaoki would you mind sponsoring the upload ?

**Comment by osamuaoki** [comment]
Hi,

I test buit this package.  I seee a few:

W: /bin/mksh: setlocale: No such file or directory


Is this OK?

**Comment by williamdes** [comment]
> Hi, I test buit this package. I seee a few: W: /bin/mksh: setlocale: No such file or directory Is this OK?

Hi,

It seems like it is okay, a version was uploaded to Debian experimental already. Could you push the new changes I made to experimental or unstable since nobody did complain about the experimental version?

**Comment by williamdes** [comment]
Hi @osamuaoki 
Did you have an occasion to send shunit2 from experimental into unstable ?

**Comment by osamuaoki** [comment]
Not yet (I recently moved and has been busy.)
Give me some time

**Comment by williamdes** [comment]
I think we can consider this issue as done: https://tracker.debian.org/news/1389384/accepted-shunit2-218-2-source-into-unstable/

Please test this shunit version as the next Debian version will be some time soon
