### ISSUE TITLE
Update version distributed through apt

### ISSUE THREAD

**Issue by cronholmrickard** [kward/shunit2#166]
Currently, the version of shunit2 distributed through apt is 2.1.6
I'm tempted to use shunit2 as part of CI pipeline. It's very hard to motivate installing by curling from `raw.githubusercontent.com`. Is there a plan in place to update to latest version?

**Comment by williamdes** [comment]
See #155
This is not true anymore, next Debian will have the latest release: https://tracker.debian.org/pkg/shunit2 
You can wget the DEB from https://ftp.debian.org/debian/pool/main/s/shunit2/

If you are using GitHub I make an action for shunit2: https://github.com/marketplace/actions/shunit2

**Comment by cronholmrickard** [comment]
Marked as duplicate

**Comment by williamdes** [comment]
Duplicate of #155
