### ISSUE TITLE
egrep: warning: egrep is obsolescent; using grep -E

### ISSUE THREAD

**Issue by larssb** [kward/shunit2#177]
I get the error written in the title on Ubuntu 20.04 on shunit2 from the 7th of February 2023.

egrep is used here: https://github.com/kward/shunit2/blob/master/shunit2#L1275 ... would it be possible to avoid this error?

Thanks

**Comment by williamdes** [comment]
Sure, there is a fix for it: #168
Can you test it so I can merge it with confidence ?

**Comment by larssb** [comment]
#168 totally works. I just tested it. LGTM 👍 .

---

What's the general shunit2 upgrade path? Just to download "latest" from the main/master branch?

Thanks

**Comment by williamdes** [comment]
> What's the general shunit2 upgrade path? Just to download "latest" from the main/master branch?

I guess there is no general path, but downloading a released version is better for production.
What operating system are you using ?

**Comment by williamdes** [comment]
> I guess I'm basically just looking forward to the v2.1.9 release. Correct?

Yeah. But I might pick this change into the Ubuntu and Debian packaging.

See: https://tracker.debian.org/pkg/shunit2

You can install the deb from Debian: https://packages.debian.org/trixie/all/shunit2/download

Or the Ubuntu version (exactly the same one): https://launchpad.net/ubuntu/+source/shunit2
Deb: https://launchpad.net/ubuntu/+archive/primary/+files/shunit2_2.1.8-4_all.deb
