### ISSUE TITLE
Add support for user defined prefix for test names

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kward/shunit2#29]
```
Adding a prefix for better test recognition. Prefix is added before test 
function echo.
External control is via TEST_PREFIX=<my_prefix> possible.
Default: "------ TEST :: "
```

Original issue reported on code.google.com by `Matthias...@gmail.com` on 15 Sep 2011 at 10:15

Attachments:
- [shunit2.patch](https://storage.googleapis.com/google-code-attachments/shunit2/issue-29/comment-0/shunit2.patch)

**Comment by kward** [comment]
A test prefix can now be added by defining the SHUNIT_TEST_PREFIX variable.
