### ISSUE TITLE
Readme or wiki?

### ISSUE THREAD

**Issue by DerfOh** [kward/shunit2#50]
I'm having trouble finding the documentation for this project. Could someone point me in the right direction?

**Comment by DerfOh** [comment]
Turns out there is already a PR for that. Please merge #47 :smile:

**Comment by rugk** [comment]
As https://github.com/kward/shunit2/pull/47 has been merged, this is fixed, is not it?

**Comment by kward** [comment]
Wiki added, and some initial content added.
