### ISSUE TITLE
How to run tests in other files?

### ISSUE THREAD

**Issue by richelbilderbeek** [kward/shunit2#52]
I think `shunit2` is great! 

Sadly, I cannot run tests that I put in other files. It may be that I am unaware of some `bash` functionality, or that `shunit2` cannot handle this in the way I use it.

In [a certain example](https://github.com/richelbilderbeek/shunit2_example_2) I can get `shunit2` to work on a custom function. The tests are in a file called `test`:

```bash
#!/bin/bash
. my_functions

test_is_password_incorrect()
{
    assertEquals `is_password welcome01` 0
}

test_is_password_correct()
{
    assertEquals `is_password iloverichel` 1
}

# load shunit2
. ../shunit2/source/2.1/src/shunit2
``` 

This approach works but does not scale well: I want to put these tests in another file, one file per function/unit.

In [this example](https://github.com/richelbilderbeek/shunit2_example_3) I did so. It was just moving text around.

The `test` file got shortened to this:

```
#!/bin/bash

. my_functions
. my_functions_test

# load shunit2
. ../shunit2/source/2.1/src/shunit2
```

All it does is sourcing all functions and tests. 

The tests are moved to `my_functions_test` and looks like this:

```bash
#!/bin/bash
. my_functions

test_is_password_incorrect()
{
    assertEquals `is_password welcome01` 0
}

test_is_password_correct()
{
    assertEquals `is_password iloverichel` 1
}
```

When I run the tests now, however, I read both locally and in [the Travis CI log](https://travis-ci.org/richelbilderbeek/shunit2_example_3/builds/229205559#L134) this:

```
$ ./test

Ran 0 tests.

OK
```

How come `shunit2` does not detect the test called `test_is_password_correct` function anymore? Its name does still start with `test`, so it should work. 

I hope someone can help me out. Either it is something fundamental in bash that I overlook, or I do call `shunit2` incorrectly?

**Comment by ChanderG** [comment]
I wanted the same functionality. As a workaround, explicitly adding test functions in the suite() function  seems to work. 

To make it more modular, you can source individual files with tests inside the suite() function and add the suite_addTest call in each individual test file for each local test function.

**Comment by richelbilderbeek** [comment]
@ChanderG : could you show the syntax you used (that is: an incomplete, but known-to-work) code snippet?

**Comment by ChanderG** [comment]
Setup your main runner like:
``` bash
suite()
{
  . ./tests/test1
}

. <path to shunit2>
```

And the test files like:
```bash
example1_test ()
{
  ... # test body here
}

example2_test ()
{
  ... # test body here
}

suite_addTest example1_test
suite_addTest example2_test
```

**Comment by richelbilderbeek** [comment]
Awesome, thanks! I'll close this Issue then :+1:

**Comment by richelbilderbeek** [comment]
Note to self: put it here: https://github.com/richelbilderbeek/shunit2_example_4
