### ISSUE TITLE
Add colouring to output

### ISSUE THREAD

**Issue by alexharv074** [kward/shunit2#56]
Request to add this commit from here:
https://github.com/dacacioa/shunit2/commit/413fd1104369b7f2349f484636b42f5dd79bf601

**Comment by alexharv074** [comment]
Actually, that patch breaks the tests.

**Comment by dacacioa** [comment]
I fixed the code to pass all the tests.

**Comment by kward** [comment]
Thanks for the patch! I've enabled color by default going forward.

I tweaked it a bit to support the following:
- Allow users to set the SHUNIT_COLOR to 'always', 'auto', or 'none', with 'auto' being the default.
- Auto detect whether color can even be shown based on the output of the 'tput colors' command.
- Auto detect whether the '-e' option is supported on echo or not.

**Comment by alexharv074** [comment]
I just upgraded to point to latest shunit2-2.7-pre - colouring is so awesome, thanks @dacacioa , @kward !

**Comment by kward** [comment]
Thanks to both @alexharv074 and @dacacioa for providing the original code!
