### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by rugk** [kward/shunit2#61]
Please [tag](https://git-scm.com/book/en/v2/Git-Basics-Tagging) your [releases](https://help.github.com/articles/about-releases/), so they can be seen [on GitHub](https://help.github.com/articles/creating-releases/).

Currently we see "source" and "website", which is not useful and which also is not the way tags in git should be used.

**Comment by kward** [comment]
Hi rugk,

Thank you for your feedback.

I agree that tags would be nice, and plan to use them going forward. Unfortunately, GitHub didn't support them when I imported shunit2 from Sourceforge back in 2011 (support arrived in 2013), so none of my tags made it across. I tagging the [v2.1.6](../releases/tag/v2.1.6) release by hand, but it references the full historical source (1.x version included).

I also realize that the source isn't laid out to GitHub standards, but when I created shunit2 more than a decade ago, GitHub didn't exist. That said, I'll look into the GitHub best practices for supporting multiple versions simultaneously to see how to best restructure the codebase.

I'll leave this issue open until I've restructured things.

**Comment by rugk** [comment]
> GitHub didn't support them when I imported shunit2 from SourceForge back in 2011

I think it should work when you have a local copy with them. Just `git push --tags`.

And generally git tags do not have anything to do with GitHub. Also other source code hosting platforms use them.

**Comment by kward** [comment]
Code is restructured. Active development will remain on the master branch, with all 2.0.x changes (likely none to follow) on the 2.0.x branch.

When I make a future 2.1.7 release, I will tag it appropriately.

**Comment by kward** [comment]
2.1.7 release made and properly signed and tagged.
https://github.com/kward/shunit2/releases/tag/v2.1.7
