### ISSUE TITLE
Sign git commits & tags (releases)

### ISSUE THREAD

**Issue by rugk** [kward/shunit2#64]
You should consider signing git commits & releases.

* [onionshare#221 (comment)](https://is.gd/7vU4oK)
* It is also displayed on GitHub: https://github.com/blog/2144-gpg-signature-verification
* Here is GitHub's help for this: https://help.github.com/articles/signing-commits-with-gpg/
* And here is how you can properly sign releases: https://wiki.debian.org/Creating%20signed%20GitHub%20releases ([and here is a script for that](https://github.com/rugk/gittools/blob/master/signrelease.sh))
* When used in unit tests, we can easily verify the integrity/authenticity of shunit2

**Comment by kward** [comment]
2.1.7 release made and properly signed and tagged.
https://github.com/kward/shunit2/releases/tag/v2.1.7
