### ISSUE TITLE
Version library fails for bash shell…

### ISSUE THREAD

**Issue by rugk** [kward/shunit2#65]
When is the [version library](https://github.com/kward/shunit2/blob/master/lib/versions) used? Because it always fails when I test it.

```
$ versions_shell_zsh /usr/bin/bash
bash,
(C)
GPLv3+:

ist
wird

```

(zsh BTW works)

Real result:
```
$ bash --version
GNU bash, Version 4.4.12(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2016 Free Software Foundation, Inc.
Lizenz GPLv3+: GNU GPL Version 3 oder jünger <http://gnu.org/licenses/gpl.html>

Dies ist freie Software.  Sie darf verändert und verteilt werden.
Es wird keine Garantie gewährt, soweit das Gesetz es zulässt.
```

Fedora 26

**Comment by rugk** [comment]
Why do you do this ugly man page parsing etc. anyway. Why not just execute e.g. `bash -c 'echo $BASH_VERSION'`?

```
$ bash -c 'echo $BASH_VERSION'
4.4.12(1)-release
```

**Comment by kward** [comment]
`versions_shell_zsh` is for detecting the version of `zsh`, not `bash`. Use `versions_shell_bash` if you want to detect the `bash` version.

Also, I'm not sure what you are talking about with man page parsing. I don't do anything with man pages in the `versions` script.

As far as improving the `bash` detection, feel free to send a patch to my https://github.com/kward/shlib repo.

**Comment by rugk** [comment]
Ah, right, no man pages…
