### ISSUE TITLE
No color output in Travis-CI

### ISSUE THREAD

**Issue by rugk** [kward/shunit2#67]
How do you determinate whether the shell supports colored output?
Currently in my Travis-CI tests everything is just black and white.

v https://github.com/kward/shunit2/commit/697249da081473c1904d84e9aa2dd4633a3115fb

**Comment by kward** [comment]
Color detection is in the `_shunit_configureColor()` function. I'm guessing that the `tput` command isn't available, and without it, output colouring is disabled.

You can force color to be enabled by setting the SHUNIT_COLOR variable. See
https://github.com/kward/shunit2/blob/master/.travis.yml for how to do that.
