### ISSUE TITLE
Run shellcheck

### ISSUE THREAD

**Issue by rugk** [kward/shunit2#68]
[Shellcheck](https://www.shellcheck.net/) finds some issues in your code. E.g. you often use backticks, however, these are discouraged (e.g. they are hard to see) and `$( )` should be preferred.

You could even include shellcheck in CI testing in Travis CI or similar.

**Comment by kward** [comment]
Thank you for the suggestion. I'll run the code through, but I won't be fixing everything recommended by that tool. My code is designed to be as portable as possible, and `$()` for example is not portable shell.

Under the Bourne shell (not the Bourne Again shell, a.k.a. bash), this is the error that `$()` generates:
```
$ echo $(ls)
syntax error: `(' unexpected
```

**Comment by rugk** [comment]
Actually AFAIK `$( )` is POSIX-compatible. I use it in unit tests in Travis and it works. And shellcheck checks if you use the `/bin/sh` shebang that no "bashism" happens.

Maybe you need spaces inside of it? `$( ls )`.

**Comment by rugk** [comment]
BTW and if you really have valid reasons to not follow shellcheck in one case, [exclude the check](https://github.com/koalaman/shellcheck/wiki/Directive) and preferably add a comment explaining the case.

BTW feel free to include [shellcheck in your Travis CI tests](https://github.com/rugk/borg-cron-helper/blob/master/tests/testShellcheck.sh) ([second file I used](https://github.com/rugk/borg-cron-helper/blob/master/tests/testShellcheckExec.sh))…

**Comment by kward** [comment]
POSIX != portable, and Solaris for one always provided a default `/bin/sh` shell that was not POSIX compatible. Solaris was only recently cancelled by Oracle, so I'll keep the backward compatibility for a while longer.

**Comment by kward** [comment]
All scripts now run through shellcheck as part of continuous integration.
