### ISSUE TITLE
Shunit should allow to run parameterized tests

### ISSUE THREAD

**Issue by mzanini** [kward/shunit2#70]
I have a series of tests that I would like to run for different values of a certain variable, for example: 

#file test-create-file.sh
testFileCreatedIfArgumentsValid() {
    bash ./create-file.sh $arch
    assertTrue 'config file has not been created' "[ -f ${filename} ]"
}

I would like to run the test with arch=x86_64 and arch=i686. I have discovered no options to do this. I cannot pass parameters to the test-create-file.sh because shunit2 gives an error, I think this might be because the shunit2 script uses the $1 variable. 

I cannot duplicate the test because I have many test cases with the same issue, I suppose I could duplicate the test file itself but that would create unnecessary duplication. 

It would be nice to have something similar to Google Test's [parameterized tests].(https://github.com/google/googletest/blob/master/googletest/docs/AdvancedGuide.md).

Please feel free to comment with a workaround if that exists.

Thank you!
Marco

**Comment by kward** [comment]
Does this wiki entry solve your problem?
https://github.com/kward/shunit2/wiki/Cookbook#passing-arguments-to-test-script

**Comment by mzanini** [comment]
Yes, that seems to be working, thank you very much! Don't know why that didn't get my attention.

**Comment by kward** [comment]
I wrote the entry based on this issue, which is why you probably hadn't seen it before.
