### ISSUE TITLE
Ubuntu trusty (Travis) /dev/mem: no such file 

### ISSUE THREAD

**Issue by Pitterling** [kward/shunit2#74]
Hi,

i just tried an Travis CI on trusty and get this error message: **/dev/mem: No such file or directory**
Obviously this file has not been created ... but the test does not fail .. shunit2 is not directly reading that file, so what is causing this and would this be required at all?

```
#------------------------------------------------------------------------------
# Running the test suite with /bin/bash.
#

shell name: bash
shell version: 4.3.11(1)-release

--- Executing the 'CompareVersions' test suite. ---
/dev/mem: No such file or directory
/dev/mem: No such file or directory
testCompareVersionsEqualTo
testCompareVersionsLessThan
testCompareVersionsGreaterThan
testCompareVersionsShouldFail

Ran 4 tests.
OK
```

Any clue/hint to investigate further?

Thx, P

**Comment by kward** [comment]
I have no idea. Would you be willing to share the code you are working on?

**Comment by Pitterling** [comment]
Will look into this once I’m back from vacation.

**Comment by Pitterling** [comment]
a 'dmidecode' call within my sourced files is responsible for this .. therefore this is not related to shunit2 itself. Closing.
