### ISSUE TITLE
Publish public key

### ISSUE THREAD

**Issue by rugk** [kward/shunit2#76]
In order to verify the signed (https://github.com/kward/shunit2/issues/64) tags, you of course also have to publish your public key. I could not find it anywhere, so…?

**Comment by kward** [comment]
http://hkps.pool.sks-keyservers.net/pks/lookup?search=0xe0f8ce4b&op=vindex
http://hkps.pool.sks-keyservers.net/pks/lookup?op=get&search=0xE52196194E1B251C
