### ISSUE TITLE
Tool to support aggregation of tests

### ISSUE THREAD

**Issue by GoogleCodeExporter** [kward/shunit2#8]
```
The tool would be similar to the shunit_test.sh tool already provided, but 
would aggregate results 
and produce a final report.

```

Original issue reported on code.google.com by `kate.a.w...@gmail.com` on 7 Oct 2008 at 11:37

**Comment by kward** [comment]
I've released my test_runner (https://github.com/kward/shlib/blob/master/standalone/test_runner) code as a standalone script, which should cover this need.
