### ISSUE TITLE
License does not specify version of LGPL

### ISSUE THREAD

**Issue by awilfox** [kward/shunit2#94]
At [lib/shlib#L4](https://github.com/kward/shunit2/blob/07bb3292048a4982aad7247bdd7890f2bf532ece/lib/shlib#L4), the file is simply licensed under "the LGPL".

We're trying to package shunit2 [for our Linux distribution](https://code.foxkit.us/adelie/packages/merge_requests/53#note_1927), and we have a policy of always specifying the [SPDX identifier](https://spdx.org/licenses/) for every package.  This package would be "Apache-2.0 AND ".... which LGPL?

**Comment by kward** [comment]
I need to fix some other files too…
